-- ============================================================
-- TRIGGERS DE CLASIFICACION
-- Sistema de Pronosticos / Apuestas de Torneos de Futbol
-- PostgreSQL
--
-- Ejecutar en la base del proyecto:
--   psql -U postgres -d ligamundial_bd -f backend/sql/clasificacion_triggers.sql
--
-- Objetivo:
--   1. Poblar/actualizar puntaje cuando se registra o cambia un resultado oficial.
--   2. Poblar/actualizar puntaje cuando se registra o cambia un vaticinio y ya existe resultado.
--   3. Guardar snapshot en clasificacion_historico por liga y partido para alimentar tendencia.
-- ============================================================

-- Asegura la tabla historica segun el esquema actual de la base.
CREATE TABLE IF NOT EXISTS clasificacion_historico (
    id_historico INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_liga INT NOT NULL REFERENCES liga(id_liga) ON UPDATE CASCADE ON DELETE CASCADE,
    id_liga_miembro INT NOT NULL REFERENCES liga_miembro(id_liga_miembro) ON UPDATE CASCADE ON DELETE CASCADE,
    id_partido INT NOT NULL REFERENCES partido(id_partido) ON UPDATE CASCADE ON DELETE CASCADE,
    posicion_anterior INT,
    posicion_actual INT NOT NULL,
    puntos_acumulados INT NOT NULL DEFAULT 0,
    aciertos_exactos INT NOT NULL DEFAULT 0,
    aciertos_resultado INT NOT NULL DEFAULT 0,
    movimiento INT NOT NULL DEFAULT 0,
    fecha_calculo TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_clasificacion_historico UNIQUE (id_liga, id_liga_miembro, id_partido),
    CONSTRAINT chk_clasificacion_posicion_actual CHECK (posicion_actual > 0),
    CONSTRAINT chk_clasificacion_posicion_anterior CHECK (posicion_anterior IS NULL OR posicion_anterior > 0),
    CONSTRAINT chk_clasificacion_puntos_acumulados CHECK (puntos_acumulados >= 0),
    CONSTRAINT chk_clasificacion_aciertos_exactos CHECK (aciertos_exactos >= 0),
    CONSTRAINT chk_clasificacion_aciertos_resultado CHECK (aciertos_resultado >= 0)
);

CREATE INDEX IF NOT EXISTS idx_clasificacion_historico_liga
    ON clasificacion_historico(id_liga);

CREATE INDEX IF NOT EXISTS idx_clasificacion_historico_liga_miembro
    ON clasificacion_historico(id_liga_miembro);

CREATE INDEX IF NOT EXISTS idx_clasificacion_historico_partido
    ON clasificacion_historico(id_partido);

CREATE INDEX IF NOT EXISTS idx_clasificacion_historico_liga_partido
    ON clasificacion_historico(id_liga, id_partido);

CREATE INDEX IF NOT EXISTS idx_clasificacion_historico_fecha
    ON clasificacion_historico(fecha_calculo);


-- ============================================================
-- 1. Calcula puntajes para todos los vaticinios de un partido.
--    Regla actual del backend:
--      marcador exacto = 3 puntos
--      resultado correcto = 1 punto
--      fallo = 0 puntos
-- ============================================================
CREATE OR REPLACE FUNCTION fn_recalcular_puntajes_partido(p_id_partido INT)
RETURNS VOID AS $$
BEGIN
    INSERT INTO puntaje (
        id_vaticinio,
        puntos,
        acerto_resultado,
        acerto_marcador,
        fecha_calculo
    )
    SELECT
        v.id_vaticinio,
        CASE
            WHEN v.goles_local_pred = ro.goles_local
             AND v.goles_visitante_pred = ro.goles_visitante
                THEN 3
            WHEN SIGN(v.goles_local_pred - v.goles_visitante_pred)
               = SIGN(ro.goles_local - ro.goles_visitante)
                THEN 1
            ELSE 0
        END AS puntos,
        (
            SIGN(v.goles_local_pred - v.goles_visitante_pred)
            = SIGN(ro.goles_local - ro.goles_visitante)
        ) AS acerto_resultado,
        (
            v.goles_local_pred = ro.goles_local
            AND v.goles_visitante_pred = ro.goles_visitante
        ) AS acerto_marcador,
        NOW()
    FROM vaticinio v
    JOIN resultado_oficial ro
        ON ro.id_partido = v.id_partido
    WHERE v.id_partido = p_id_partido
    ON CONFLICT (id_vaticinio) DO UPDATE SET
        puntos = EXCLUDED.puntos,
        acerto_resultado = EXCLUDED.acerto_resultado,
        acerto_marcador = EXCLUDED.acerto_marcador,
        fecha_calculo = NOW();
END;
$$ LANGUAGE plpgsql;


-- ============================================================
-- 2. Guarda snapshot de clasificacion por liga afectada.
--    Se guarda una fila por miembro activo y partido.
-- ============================================================
CREATE OR REPLACE FUNCTION fn_guardar_clasificacion_partido(p_id_partido INT)
RETURNS VOID AS $$
BEGIN
    INSERT INTO clasificacion_historico (
        id_liga,
        id_liga_miembro,
        id_partido,
        posicion_anterior,
        posicion_actual,
        puntos_acumulados,
        aciertos_exactos,
        aciertos_resultado,
        movimiento,
        fecha_calculo
    )
    WITH ligas_afectadas AS (
        SELECT DISTINCT lm.id_liga
        FROM vaticinio v
        JOIN liga_miembro lm
            ON lm.id_liga_miembro = v.id_liga_miembro
        WHERE v.id_partido = p_id_partido
    ),
    totales AS (
        SELECT
            lm.id_liga,
            lm.id_liga_miembro,
            COALESCE(SUM(p.puntos), 0)::INT AS puntos_acumulados,
            COALESCE(SUM(CASE WHEN p.acerto_marcador THEN 1 ELSE 0 END), 0)::INT AS aciertos_exactos,
            COALESCE(SUM(CASE WHEN p.acerto_resultado THEN 1 ELSE 0 END), 0)::INT AS aciertos_resultado
        FROM liga_miembro lm
        JOIN ligas_afectadas la
            ON la.id_liga = lm.id_liga
        LEFT JOIN vaticinio v
            ON v.id_liga_miembro = lm.id_liga_miembro
        LEFT JOIN puntaje p
            ON p.id_vaticinio = v.id_vaticinio
        WHERE lm.estado_membresia = 'activo'
        GROUP BY lm.id_liga, lm.id_liga_miembro
    ),
    ranking AS (
        SELECT
            ROW_NUMBER() OVER (
                PARTITION BY t.id_liga
                ORDER BY
                    t.puntos_acumulados DESC,
                    t.aciertos_exactos DESC,
                    t.aciertos_resultado DESC,
                    t.id_liga_miembro ASC
            )::INT AS posicion_actual,
            t.*
        FROM totales t
    ),
    anterior AS (
        SELECT DISTINCT ON (ch.id_liga_miembro)
            ch.id_liga_miembro,
            ch.posicion_actual AS posicion_anterior
        FROM clasificacion_historico ch
        WHERE ch.id_partido <> p_id_partido
          AND ch.id_liga IN (SELECT id_liga FROM ligas_afectadas)
        ORDER BY ch.id_liga_miembro, ch.fecha_calculo DESC, ch.id_historico DESC
    )
    SELECT
        r.id_liga,
        r.id_liga_miembro,
        p_id_partido,
        a.posicion_anterior,
        r.posicion_actual,
        r.puntos_acumulados,
        r.aciertos_exactos,
        r.aciertos_resultado,
        COALESCE(a.posicion_anterior - r.posicion_actual, 0)::INT AS movimiento,
        NOW()
    FROM ranking r
    LEFT JOIN anterior a
        ON a.id_liga_miembro = r.id_liga_miembro
    ON CONFLICT (id_liga, id_liga_miembro, id_partido) DO UPDATE SET
        posicion_anterior = EXCLUDED.posicion_anterior,
        posicion_actual = EXCLUDED.posicion_actual,
        puntos_acumulados = EXCLUDED.puntos_acumulados,
        aciertos_exactos = EXCLUDED.aciertos_exactos,
        aciertos_resultado = EXCLUDED.aciertos_resultado,
        movimiento = EXCLUDED.movimiento,
        fecha_calculo = NOW();
END;
$$ LANGUAGE plpgsql;


-- ============================================================
-- 3. Trigger al insertar/actualizar resultado oficial.
-- ============================================================
CREATE OR REPLACE FUNCTION trg_resultado_actualiza_clasificacion_fn()
RETURNS TRIGGER AS $$
BEGIN
    PERFORM fn_recalcular_puntajes_partido(NEW.id_partido);
    PERFORM fn_guardar_clasificacion_partido(NEW.id_partido);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_resultado_actualiza_clasificacion ON resultado_oficial;
CREATE TRIGGER trg_resultado_actualiza_clasificacion
AFTER INSERT OR UPDATE OF goles_local, goles_visitante
ON resultado_oficial
FOR EACH ROW
EXECUTE FUNCTION trg_resultado_actualiza_clasificacion_fn();


-- ============================================================
-- 4. Trigger al insertar/actualizar vaticinio.
--    Si ya existe resultado oficial para el partido, recalcula.
-- ============================================================
CREATE OR REPLACE FUNCTION trg_vaticinio_actualiza_clasificacion_fn()
RETURNS TRIGGER AS $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM resultado_oficial ro
        WHERE ro.id_partido = NEW.id_partido
    ) THEN
        PERFORM fn_recalcular_puntajes_partido(NEW.id_partido);
        PERFORM fn_guardar_clasificacion_partido(NEW.id_partido);
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_vaticinio_actualiza_clasificacion ON vaticinio;
CREATE TRIGGER trg_vaticinio_actualiza_clasificacion
AFTER INSERT OR UPDATE OF goles_local_pred, goles_visitante_pred, id_partido, id_liga_miembro
ON vaticinio
FOR EACH ROW
EXECUTE FUNCTION trg_vaticinio_actualiza_clasificacion_fn();


-- ============================================================
-- 5. Carga inicial para datos existentes.
-- ============================================================
DO $$
DECLARE
    r RECORD;
BEGIN
    FOR r IN
        SELECT id_partido
        FROM resultado_oficial
    LOOP
        PERFORM fn_recalcular_puntajes_partido(r.id_partido);
        PERFORM fn_guardar_clasificacion_partido(r.id_partido);
    END LOOP;
END $$;
