-- ============================================================
-- Tabla de asignacion de paises a grupos
-- ============================================================
-- Permite validar que un partido de grupo use solo paises
-- asignados al mismo grupo, sin agregar campos a partido.

CREATE TABLE IF NOT EXISTS pais_grupo (
    id_pais_grupo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pais INT NOT NULL,
    id_grupo INT NOT NULL,
    fecha_asignacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_pais_grupo UNIQUE (id_pais, id_grupo),
    CONSTRAINT uq_grupo_pais UNIQUE (id_grupo, id_pais),

    CONSTRAINT fk_pais_grupo_pais
        FOREIGN KEY (id_pais)
        REFERENCES pais(id_pais)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_pais_grupo_grupo
        FOREIGN KEY (id_grupo)
        REFERENCES grupo(id_grupo)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_pais_grupo_grupo
    ON pais_grupo(id_grupo);

CREATE INDEX IF NOT EXISTS idx_pais_grupo_pais
    ON pais_grupo(id_pais);

INSERT INTO pais_grupo (id_pais, id_grupo)
SELECT id_pais, id_grupo
FROM pais
WHERE id_grupo IS NOT NULL
ON CONFLICT (id_pais, id_grupo) DO NOTHING;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_partido_local_pais_grupo'
    ) THEN
        ALTER TABLE partido
        ADD CONSTRAINT fk_partido_local_pais_grupo
        FOREIGN KEY (id_grupo, id_equipo_local)
        REFERENCES pais_grupo(id_grupo, id_pais)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
        NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_partido_visitante_pais_grupo'
    ) THEN
        ALTER TABLE partido
        ADD CONSTRAINT fk_partido_visitante_pais_grupo
        FOREIGN KEY (id_grupo, id_equipo_visitante)
        REFERENCES pais_grupo(id_grupo, id_pais)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
        NOT VALID;
    END IF;
END $$;
