-- ============================================================
-- SCRIPT DE CREACIÓN DE BASE DE DATOS
-- Sistema de Pronósticos / Apuestas de Torneos de Fútbol
-- PostgreSQL
-- ligaMundial_BD = nombre base de datos
-- ============================================================

-- Extensión para generar tokens automáticos
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ============================================================
-- LIMPIEZA OPCIONAL
-- Si ya habías creado tablas antes, esto las elimina.
-- ============================================================

DROP TABLE IF EXISTS distribucion_premio CASCADE;
DROP TABLE IF EXISTS premio CASCADE;
DROP TABLE IF EXISTS cierre_liga CASCADE;
DROP TABLE IF EXISTS invitacion_liga CASCADE;
DROP TABLE IF EXISTS solicitud_ingreso CASCADE;
DROP TABLE IF EXISTS puntaje CASCADE;
DROP TABLE IF EXISTS vaticinio CASCADE;
DROP TABLE IF EXISTS liga_miembro CASCADE;
DROP TABLE IF EXISTS resultado_oficial CASCADE;
DROP TABLE IF EXISTS partido CASCADE;
DROP TABLE IF EXISTS liga CASCADE;
DROP TABLE IF EXISTS usuario CASCADE;
DROP TABLE IF EXISTS rol CASCADE;
DROP TABLE IF EXISTS estadio CASCADE;
DROP TABLE IF EXISTS sede CASCADE;
DROP TABLE IF EXISTS pais_grupo CASCADE;
DROP TABLE IF EXISTS pais CASCADE;
DROP TABLE IF EXISTS grupo CASCADE;
DROP TABLE IF EXISTS fase CASCADE;
DROP TABLE IF EXISTS torneo CASCADE;

-- ============================================================
-- 1. ROL
-- ============================================================

CREATE TABLE rol (
    id_rol INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_rol VARCHAR(50) NOT NULL UNIQUE,
    descripcion VARCHAR(150),
    estado BOOLEAN NOT NULL DEFAULT TRUE
);

-- ============================================================
-- 2. USUARIO
-- ============================================================

CREATE TABLE usuario (
    id_usuario INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_completo VARCHAR(100) NOT NULL,
    email VARCHAR(120) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'activo',
    id_rol INT NOT NULL,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_usuario_rol
        FOREIGN KEY (id_rol)
        REFERENCES rol(id_rol)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

-- ============================================================
-- 3. TORNEO
-- ============================================================

CREATE TABLE torneo (
    id_torneo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    anio INT NOT NULL,
    estado VARCHAR(20) NOT NULL
);

-- ============================================================
-- 4. FASE
-- ============================================================

CREATE TABLE fase (
    id_fase INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_torneo INT NOT NULL,
    nombre VARCHAR(50) NOT NULL,
    orden_fase INT NOT NULL,

    CONSTRAINT fk_fase_torneo
        FOREIGN KEY (id_torneo)
        REFERENCES torneo(id_torneo)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- ============================================================
-- 5. GRUPO
-- ============================================================

CREATE TABLE grupo (
    id_grupo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_torneo INT NOT NULL,
    nombre VARCHAR(20) NOT NULL,

    CONSTRAINT fk_grupo_torneo
        FOREIGN KEY (id_torneo)
        REFERENCES torneo(id_torneo)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- ============================================================
-- 6. PAIS
-- ============================================================

CREATE TABLE pais (
    id_pais INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    codigo_fifa CHAR(3) NOT NULL UNIQUE,
    confederacion VARCHAR(50),
    id_grupo INT,

    CONSTRAINT fk_pais_grupo
        FOREIGN KEY (id_grupo)
        REFERENCES grupo(id_grupo)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);

-- ============================================================
-- 7. PAIS_GRUPO
-- ============================================================

CREATE TABLE pais_grupo (
    id_pais_grupo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pais INT NOT NULL,
    id_grupo INT NOT NULL,
    fecha_asignacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_pais_grupo UNIQUE (id_pais, id_grupo),
    CONSTRAINT uq_grupo_pais UNIQUE (id_grupo, id_pais),

    CONSTRAINT fk_pais_grupo_pais
        FOREIGN KEY (id_pais)
        REFERENCES pais(id_pais)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_pais_grupo_grupo
        FOREIGN KEY (id_grupo)
        REFERENCES grupo(id_grupo)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- ============================================================
-- 8. SEDE
-- ============================================================

CREATE TABLE sede (
    id_sede INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    ciudad VARCHAR(100) NOT NULL,
    pais_sede VARCHAR(100) NOT NULL
);

-- ============================================================
-- 9. ESTADIO
-- ============================================================

CREATE TABLE estadio (
    id_estadio INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sede INT NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    capacidad INT,

    CONSTRAINT fk_estadio_sede
        FOREIGN KEY (id_sede)
        REFERENCES sede(id_sede)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- ============================================================
-- 10. LIGA
-- ============================================================

CREATE TABLE liga (
    id_liga INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    tipo_liga VARCHAR(20) NOT NULL,
    precio_participacion NUMERIC(10,2) DEFAULT 0.00,
    id_creador_usuario INT NOT NULL,
    id_admin_usuario INT NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'activa',
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_liga_creador
        FOREIGN KEY (id_creador_usuario)
        REFERENCES usuario(id_usuario)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_liga_admin
        FOREIGN KEY (id_admin_usuario)
        REFERENCES usuario(id_usuario)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

-- ============================================================
-- 11. LIGA_MIEMBRO
-- ============================================================

CREATE TABLE liga_miembro (
    id_liga_miembro INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_liga INT NOT NULL,
    id_usuario INT NOT NULL,
    nombre_equipo VARCHAR(50) NOT NULL,
    rol_liga VARCHAR(20) NOT NULL,
    estado_membresia VARCHAR(20) NOT NULL DEFAULT 'activo',
    fecha_union DATE NOT NULL DEFAULT CURRENT_DATE,

    CONSTRAINT uq_liga_usuario UNIQUE (id_liga, id_usuario),
    CONSTRAINT uq_liga_nombre_equipo UNIQUE (id_liga, nombre_equipo),

    CONSTRAINT fk_liga_miembro_liga
        FOREIGN KEY (id_liga)
        REFERENCES liga(id_liga)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_liga_miembro_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuario(id_usuario)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- ============================================================
-- 12. INVITACION_LIGA
-- ============================================================

CREATE TABLE invitacion_liga (
    id_invitacion INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_liga INT NOT NULL,
    email_destino VARCHAR(120) NOT NULL,
    token VARCHAR(150) NOT NULL UNIQUE DEFAULT gen_random_uuid()::TEXT,
    fecha_envio TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    estado VARCHAR(20) NOT NULL DEFAULT 'pendiente',

    CONSTRAINT fk_invitacion_liga
        FOREIGN KEY (id_liga)
        REFERENCES liga(id_liga)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- ============================================================
-- 13. SOLICITUD_INGRESO
-- ============================================================

CREATE TABLE solicitud_ingreso (
    id_solicitud INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_liga INT NOT NULL,
    id_usuario INT NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'pendiente',
    fecha_solicitud TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_resolucion TIMESTAMPTZ,

    CONSTRAINT fk_solicitud_liga
        FOREIGN KEY (id_liga)
        REFERENCES liga(id_liga)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_solicitud_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuario(id_usuario)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- ============================================================
-- 14. PARTIDO
-- ============================================================

CREATE TABLE partido (
    id_partido INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_torneo INT NOT NULL,
    id_fase INT NOT NULL,
    id_grupo INT,
    id_estadio INT NOT NULL,
    id_equipo_local INT NOT NULL,
    id_equipo_visitante INT NOT NULL,
    fecha_hora_inicio TIMESTAMPTZ NOT NULL,
    estado_partido VARCHAR(20) NOT NULL DEFAULT 'programado',

    CONSTRAINT fk_partido_torneo
        FOREIGN KEY (id_torneo)
        REFERENCES torneo(id_torneo)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_partido_fase
        FOREIGN KEY (id_fase)
        REFERENCES fase(id_fase)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_partido_grupo
        FOREIGN KEY (id_grupo)
        REFERENCES grupo(id_grupo)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_partido_estadio
        FOREIGN KEY (id_estadio)
        REFERENCES estadio(id_estadio)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_partido_local
        FOREIGN KEY (id_equipo_local)
        REFERENCES pais(id_pais)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_partido_visitante
        FOREIGN KEY (id_equipo_visitante)
        REFERENCES pais(id_pais)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_partido_equipos_diferentes
        CHECK (id_equipo_local <> id_equipo_visitante)
);

ALTER TABLE partido
    ADD CONSTRAINT fk_partido_local_pais_grupo
    FOREIGN KEY (id_grupo, id_equipo_local)
    REFERENCES pais_grupo(id_grupo, id_pais)
    ON UPDATE CASCADE
    ON DELETE RESTRICT;

ALTER TABLE partido
    ADD CONSTRAINT fk_partido_visitante_pais_grupo
    FOREIGN KEY (id_grupo, id_equipo_visitante)
    REFERENCES pais_grupo(id_grupo, id_pais)
    ON UPDATE CASCADE
    ON DELETE RESTRICT;

-- ============================================================
-- 15. RESULTADO_OFICIAL
-- ============================================================

CREATE TABLE resultado_oficial (
    id_resultado INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_partido INT NOT NULL UNIQUE,
    goles_local INT NOT NULL,
    goles_visitante INT NOT NULL,
    fecha_registro TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    bloqueado BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT fk_resultado_partido
        FOREIGN KEY (id_partido)
        REFERENCES partido(id_partido)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT chk_resultado_goles
        CHECK (goles_local >= 0 AND goles_visitante >= 0)
);

-- ============================================================
-- 16. VATICINIO
-- ============================================================

CREATE TABLE vaticinio (
    id_vaticinio INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_liga_miembro INT NOT NULL,
    id_partido INT NOT NULL,
    goles_local_pred INT NOT NULL,
    goles_visitante_pred INT NOT NULL,
    fecha_registro TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_modificacion TIMESTAMPTZ,

    CONSTRAINT uq_vaticinio_miembro_partido UNIQUE (id_liga_miembro, id_partido),

    CONSTRAINT fk_vaticinio_liga_miembro
        FOREIGN KEY (id_liga_miembro)
        REFERENCES liga_miembro(id_liga_miembro)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_vaticinio_partido
        FOREIGN KEY (id_partido)
        REFERENCES partido(id_partido)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT chk_vaticinio_goles
        CHECK (goles_local_pred >= 0 AND goles_visitante_pred >= 0)
);

-- ============================================================
-- 16. PUNTAJE
-- ============================================================

CREATE TABLE puntaje (
    id_puntaje INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_vaticinio INT NOT NULL UNIQUE,
    puntos INT NOT NULL DEFAULT 0,
    acerto_resultado BOOLEAN NOT NULL DEFAULT FALSE,
    acerto_marcador BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_calculo TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_puntaje_vaticinio
        FOREIGN KEY (id_vaticinio)
        REFERENCES vaticinio(id_vaticinio)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT chk_puntaje_no_negativo
        CHECK (puntos >= 0)
);

-- ============================================================
-- 17. CIERRE_LIGA
-- ============================================================

CREATE TABLE cierre_liga (
    id_cierre_liga INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_liga INT NOT NULL UNIQUE,
    total_recaudado NUMERIC(10,2) DEFAULT 0.00,
    comision NUMERIC(10,2) DEFAULT 0.00,
    fondo_global NUMERIC(10,2) DEFAULT 0.00,
    monto_neto NUMERIC(10,2) DEFAULT 0.00,
    promedio_puntos NUMERIC(10,2) DEFAULT 0.00,
    fecha_cierre TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_cierre_liga
        FOREIGN KEY (id_liga)
        REFERENCES liga(id_liga)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- ============================================================
-- 18. DISTRIBUCION_PREMIO
-- ============================================================

CREATE TABLE distribucion_premio (
    id_distribucion INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cierre_liga INT NOT NULL,
    posicion_final INT NOT NULL,
    porcentaje NUMERIC(5,2) NOT NULL,
    monto NUMERIC(10,2) NOT NULL,
    descripcion VARCHAR(100),

    CONSTRAINT fk_distribucion_cierre
        FOREIGN KEY (id_cierre_liga)
        REFERENCES cierre_liga(id_cierre_liga)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT chk_distribucion_porcentaje
        CHECK (porcentaje >= 0 AND porcentaje <= 100),

    CONSTRAINT chk_distribucion_monto
        CHECK (monto >= 0)
);

-- ============================================================
-- 19. PREMIO
-- ============================================================

CREATE TABLE premio (
    id_premio INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_liga INT,
    id_usuario INT,
    tipo_premio VARCHAR(30) NOT NULL,
    monto NUMERIC(10,2) NOT NULL,
    descripcion VARCHAR(100),
    fecha_asignacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_premio_liga
        FOREIGN KEY (id_liga)
        REFERENCES liga(id_liga)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_premio_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuario(id_usuario)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT chk_premio_monto
        CHECK (monto >= 0)
);

-- ============================================================
-- ÍNDICES RECOMENDADOS
-- ============================================================

CREATE INDEX idx_usuario_email ON usuario(email);
CREATE INDEX idx_liga_estado ON liga(estado);
CREATE INDEX idx_liga_miembro_usuario ON liga_miembro(id_usuario);
CREATE INDEX idx_partido_torneo ON partido(id_torneo);
CREATE INDEX idx_partido_fecha ON partido(fecha_hora_inicio);
CREATE INDEX idx_vaticinio_partido ON vaticinio(id_partido);
CREATE INDEX idx_puntaje_vaticinio ON puntaje(id_vaticinio);

-- ============================================================
-- VERIFICACIÓN
-- ============================================================

SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
ORDER BY table_name;
